language: ruby
install:
  - gem uninstall bundler
  - gem install bundler --version '1.7.4'
script: "rake"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
matrix:
  include:
    - rvm: jruby-19mode
    - rvm: rbx-2
  fast_finish: true
branches:
  only: master
